---
title: "README"
author: "Michael Murphy"
date: "October 12, 2018"
output: html_document
---


```{r}
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)
```

##Data Inspection

```{r}
snp_position <- read.delim("~/BCB546X_R_Assignment/data/snp_position.txt", stringsAsFactors=FALSE)
fang_et_al_genotypes <- read.delim("~/BCB546X_R_Assignment/data/fang_et_al_genotypes.txt")

file.info("data/fang_et_al_genotypes.txt")$size
class(fang_et_al_genotypes)
dim(fang_et_al_genotypes)
str(fang_et_al_genotypes)
attributes(fang_et_al_genotypes)
sapply(fang_et_al_genotypes, class)
summary(fang_et_al_genotypes)

file.info("data/snp_position.txt")$size
class(snp_position)
dim(snp_position)
str(snp_position)
attributes(snp_position)
sapply(snp_position, class)
summary(snp_position)

snp_known <- filter(snp_position, Chromosome != "multiple", Chromosome != "unknown", Position != "multiple")
snp_known <- transform(snp_known, Chromosome = as.numeric(Chromosome), Position = as.numeric(Position))
```

##Data Processing

```{r}
fang_et_al_genotypes_maize <- filter(fang_et_al_genotypes, Group %in% c("ZMMIL", "ZMMLR", "ZMMMR"))

maize_cut <- subset(fang_et_al_genotypes_maize, select = -c(JG_OTU,Group))

maize_t <- t(maize_cut)
colnames(maize_t) <- maize_t[1,]
maize_t <- rownames_to_column(as.data.frame(maize_t), "SNP_ID")
maize_t <- maize_t[-1,]
row.names(maize_t) <- NULL

maize_snps <- inner_join(select(snp_known,"SNP_ID","Chromosome","Position"),maize_t,by = "SNP_ID")

maize_snps_ascending <- arrange(maize_snps, Chromosome, Position)

write_tsv(filter(maize_snps_ascending, Chromosome == 1), "results/C1_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 2), "results/C2_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 3), "results/C3_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 4), "results/C4_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 5), "results/C5_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 6), "results/C6_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 7), "results/C7_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 8), "results/C8_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 9), "results/C9_maize_ascending.txt")
write_tsv(filter(maize_snps_ascending, Chromosome == 10), "results/C10_maize_ascending.txt")

maize_snps_replace <- data.frame(lapply(maize_snps, function(x) {gsub("\\?", "-", x)}), stringsAsFactors = FALSE) %>% transform(Chromosome = as.numeric(Chromosome), Position = as.numeric(Position))

maize_snps_descending <- arrange(maize_snps_replace, Chromosome, desc(Position))

write_tsv(filter(maize_snps_descending, Chromosome == 1), "results/C1_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 2), "results/C2_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 3), "results/C3_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 4), "results/C4_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 5), "results/C5_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 6), "results/C6_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 7), "results/C7_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 8), "results/C8_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 9), "results/C9_maize_descending.txt")
write_tsv(filter(maize_snps_descending, Chromosome == 10), "results/C10_maize_descending.txt")
```

```{r}
fang_et_al_genotypes_teosinte <- filter(fang_et_al_genotypes, Group %in% c("ZMPBA", "ZMPIL", "ZMPJA"))

teosinte_cut <- subset(fang_et_al_genotypes_maize, select = -c(JG_OTU,Group))

teosinte_t <- t(teosinte_cut)
colnames(teosinte_t) <- teosinte_t[1,]
teosinte_t <- rownames_to_column(as.data.frame(teosinte_t), "SNP_ID")
teosinte_t <- teosinte_t[-1,]
row.names(teosinte_t) <- NULL

teosinte_snps <- inner_join(select(snp_known,"SNP_ID","Chromosome","Position"),teosinte_t,by = "SNP_ID")

teosinte_snps_ascending <- arrange(teosinte_snps, Chromosome, Position)

write_tsv(filter(teosinte_snps_ascending, Chromosome == 1), "results/C1_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 2), "results/C2_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 3), "results/C3_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 4), "results/C4_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 5), "results/C5_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 6), "results/C6_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 7), "results/C7_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 8), "results/C8_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 9), "results/C9_teosinte_ascending.txt")
write_tsv(filter(teosinte_snps_ascending, Chromosome == 10), "results/C10_teosinte_ascending.txt")

teosinte_snps_replace <- data.frame(lapply(teosinte_snps, function(x) {gsub("\\?", "-", x)}), stringsAsFactors = FALSE) %>% transform(Chromosome = as.numeric(Chromosome), Position = as.numeric(Position))

teosinte_snps_descending <- arrange(teosinte_snps_replace, Chromosome, desc(Position))

write_tsv(filter(teosinte_snps_descending, Chromosome == 1), "results/C1_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 2), "results/C2_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 3), "results/C3_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 4), "results/C4_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 5), "results/C5_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 6), "results/C6_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 7), "results/C7_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 8), "results/C8_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 9), "results/C9_teosinte_descending.txt")
write_tsv(filter(teosinte_snps_descending, Chromosome == 10), "results/C10_teosinte_descending.txt")
```

##Data Visualization

```{r}

ggplot(data = snp_known) +   geom_bar(mapping = aes(x = Chromosome))
no_marks <- data.frame(lapply(fang_et_al_genotypes, function(x) {gsub("\\?/\\?", "", x)}), stringsAsFactors = FALSE)


no_marks1 <- sapply(filter(no_marks,Group == "ZMMIL"), function(x) length(unique(x)))
snps1 <- table(as.numeric(no_marks1[-(1:3)]))

snps1

no_marks2 <- sapply(filter(no_marks,Group == "ZMMLR"), function(x) length(unique(x)))
snps2 <- table(as.numeric(no_marks2[-(1:3)]))

snps2

no_marks3 <- sapply(filter(no_marks,Group == "ZMMMR"), function(x) length(unique(x)))
snps3 <- table(as.numeric(no_marks3[-(1:3)]))

snps3

x <- data.frame(snps1[3]+snps1[4], snps2[2]+snps2[3],snps3[3]+snps3[4])

colnames(x) <- c("ZMMIL","ZMMLR","ZMMMR") 

y <- rownames_to_column(as.data.frame(t(x)))

colnames(y)[2] <- c("Hetero")

y$newcolumn <- 986

colnames(y)[3] <- c("Total")

z <- mutate(y, Fraction = Hetero / Total)
z

ggplot(data = z) + 
  geom_point(mapping = aes(x = (rowname), y = (Fraction)))

```
